trigger:
- autocrat

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - script: |
      sudo ln -s $(command -v llvm-ar-9) /usr/bin/llvm-ar
      sudo ln -s $(command -v llvm-link-9) /usr/bin/llvm-link
      sudo ln -s $(command -v llvm-nm-9) /usr/bin/llvm-nm
      sudo ln -s $(command -v llvm-objdump-9) /usr/bin/llvm-objdump
      ./build.sh
    workingDirectory: autocrat_build
  - publish: $(System.DefaultWorkingDirectory)/autocrat_build/publish.zip
    artifact: Package (Linux)

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: ./build.cmd
    workingDirectory: autocrat_build
  - publish: $(System.DefaultWorkingDirectory)/autocrat_build/publish.zip
    artifact: Package (Windows)
